from __future__ import annotations

from pathlib import Path

from fastapi import HTTPException
from openpyxl import Workbook
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.models.entities import TestTask
from app.utils.enums import TaskStatus

settings = get_settings()


def _task_dir(task: TestTask) -> Path:
    base = Path(settings.result_base_path)
    return base / task.test_type.lower() / task.task_id


def _ensure_task_dir(task: TestTask) -> Path:
    path = _task_dir(task)
    path.mkdir(parents=True, exist_ok=True)
    return path


def generate_raw_file(db: Session, task: TestTask) -> Path:
    if task.status != TaskStatus.DONE.value:
        raise HTTPException(status_code=409, detail="Task is not completed yet")

    task_dir = _ensure_task_dir(task)
    file_path = task_dir / f"{task.test_type.lower()}_{task.task_id}_raw.txt"
    content = "\n".join(
        [
            f"task_id={task.task_id}",
            f"test_type={task.test_type}",
            f"action_type={task.action_type}",
            f"target_name={task.target_name}",
            f"status={task.status}",
            f"requested_at={task.requested_at.isoformat()}",
            "log=Mock execution completed successfully.",
            "log=This raw data file is generated by backend mock mode.",
        ]
    )
    file_path.write_text(content, encoding="utf-8")
    task.raw_result_path = str(file_path)
    db.add(task)
    db.commit()
    db.refresh(task)
    return file_path


def generate_summary_file(db: Session, task: TestTask) -> Path:
    if task.status != TaskStatus.DONE.value:
        raise HTTPException(status_code=409, detail="Task is not completed yet")

    task_dir = _ensure_task_dir(task)
    file_path = task_dir / f"{task.test_type.lower()}_{task.task_id}_summary.xlsx"

    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "summary"
    rows = [
        ("task_id", task.task_id),
        ("test_type", task.test_type),
        ("action_type", task.action_type),
        ("target_name", task.target_name),
        ("status", task.status),
        ("requested_at", task.requested_at.isoformat()),
        ("started_at", task.started_at.isoformat() if task.started_at else ""),
        ("ended_at", task.ended_at.isoformat() if task.ended_at else ""),
        ("message", task.message),
    ]
    for key, value in rows:
        sheet.append([key, value])

    workbook.save(file_path)
    task.summary_result_path = str(file_path)
    db.add(task)
    db.commit()
    db.refresh(task)
    return file_path


def get_existing_download_path(task: TestTask, kind: str) -> Path:
    if kind == "raw":
        if not task.raw_result_path:
            raise HTTPException(status_code=404, detail="Raw result file not found")
        path = Path(task.raw_result_path)
    else:
        if not task.summary_result_path:
            raise HTTPException(status_code=404, detail="Summary result file not found")
        path = Path(task.summary_result_path)

    if not path.exists():
        raise HTTPException(status_code=404, detail="Result file does not exist")

    return path

