from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

from fastapi import HTTPException
from openpyxl import Workbook
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.models.entities import RtdConfig, TestTask
from app.services.ezdfs_report_custom import build_ezdfs_test_report
from app.services.rtd_report_custom import build_rtd_test_report
from app.services.session_service import get_runtime_session_payload
from app.utils.enums import TaskStatus, TestType
from app.utils.naming import normalize_target_line_name, sanitize_path_token

settings = get_settings()


def _task_dir(task: TestTask) -> Path:
    base = Path(settings.result_base_path)
    return base / task.test_type.lower() / task.task_id


def _ensure_task_dir(task: TestTask) -> Path:
    path = _task_dir(task)
    path.mkdir(parents=True, exist_ok=True)
    return path


def generate_raw_file(
    db: Session,
    task: TestTask,
    raw_output: str | None = None,
    raw_outputs_by_rule: dict[str, str] | None = None,
) -> Path:
    if task.status != TaskStatus.DONE.value:
        raise HTTPException(status_code=409, detail="Task is not completed yet")

    line_token = sanitize_path_token(normalize_target_line_name(task.target_name))
    rule_token = sanitize_path_token(_extract_rtd_rule_name(task)) if task.test_type == "RTD" else ""
    timestamp = (task.ended_at or task.started_at or task.requested_at or datetime.now()).strftime("%Y%m%d_%H%M%S")
    task_dir = Path(settings.result_base_path) / task.test_type.lower() / "raw" / sanitize_path_token(task.user_id)
    task_dir.mkdir(parents=True, exist_ok=True)

    if (
        task.test_type == TestType.RTD.value
        and task.action_type in {"TEST", "RETEST"}
        and isinstance(raw_outputs_by_rule, dict)
        and raw_outputs_by_rule
    ):
        meta_path = _write_rtd_rule_raw_files(task_dir, task, line_token, raw_outputs_by_rule)
        task.raw_result_path = str(meta_path)
        db.add(task)
        db.commit()
        db.refresh(task)
        return meta_path

    if task.test_type == TestType.EZDFS.value and task.action_type in {"TEST", "RETEST"}:
        meta_path = _write_ezdfs_raw_files(task_dir, task, raw_output or "")
        task.raw_result_path = str(meta_path)
        db.add(task)
        db.commit()
        db.refresh(task)
        return meta_path

    file_stem = (
        f"{line_token}-{rule_token}-{timestamp}-{task.task_id[:8]}"
        if rule_token
        else f"{line_token}-{timestamp}-{task.task_id[:8]}"
    )
    file_path = task_dir / f"{file_stem}.txt"
    default_logs = [
        "log=Execution completed successfully.",
        "log=This raw data file was generated by backend execution flow.",
    ]
    content = "\n".join(
        [
            f"task_id={task.task_id}",
            f"test_type={task.test_type}",
            f"action_type={task.action_type}",
            f"target_name={task.target_name}",
            f"status={task.status}",
            f"requested_at={task.requested_at.isoformat()}",
            *([raw_output] if raw_output else default_logs),
        ]
    )
    file_path.write_text(content, encoding="utf-8")
    task.raw_result_path = str(file_path)
    db.add(task)
    db.commit()
    db.refresh(task)
    return file_path


def generate_summary_file(db: Session, task: TestTask) -> Path:
    if task.status != TaskStatus.DONE.value:
        raise HTTPException(status_code=409, detail="Task is not completed yet")

    file_path = _build_summary_output_path(db, task)

    if task.test_type == TestType.EZDFS.value:
        runtime_payload = get_runtime_session_payload(db, task.user_id, TestType.EZDFS)
        fallback_major_change_items = (
            runtime_payload.get("major_change_items")
            if isinstance(runtime_payload.get("major_change_items"), dict)
            else {}
        )
        build_ezdfs_test_report(task, file_path, None, fallback_major_change_items)
        task.summary_result_path = str(file_path)
        db.add(task)
        db.commit()
        db.refresh(task)
        return file_path

    if task.test_type == TestType.RTD.value:
        runtime_payload = get_runtime_session_payload(db, task.user_id, TestType.RTD)
        fallback_major_change_items = (
            runtime_payload.get("major_change_items")
            if isinstance(runtime_payload.get("major_change_items"), dict)
            else {}
        )
        build_rtd_test_report([task], file_path, fallback_major_change_items)
        task.summary_result_path = str(file_path)
        db.add(task)
        db.commit()
        db.refresh(task)
        return file_path

    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "summary"
    rows = [
        ("task_id", task.task_id),
        ("test_type", task.test_type),
        ("action_type", task.action_type),
        ("target_name", task.target_name),
        ("status", task.status),
        ("requested_at", task.requested_at.isoformat()),
        ("started_at", task.started_at.isoformat() if task.started_at else ""),
        ("ended_at", task.ended_at.isoformat() if task.ended_at else ""),
        ("message", task.message),
    ]
    for key, value in rows:
        sheet.append([key, value])

    workbook.save(file_path)
    task.summary_result_path = str(file_path)
    db.add(task)
    db.commit()
    db.refresh(task)
    return file_path


def _build_summary_output_path(db: Session, task: TestTask) -> Path:
    """Build the per-task summary xlsx path under `results/<type>/reports/<user>/`."""
    report_dir = Path(settings.result_base_path) / task.test_type.lower() / "reports" / sanitize_path_token(task.user_id)
    report_dir.mkdir(parents=True, exist_ok=True)

    timestamp = (task.ended_at or task.started_at or task.requested_at or datetime.now()).strftime("%Y%m%d_%H%M%S")
    name_token = _build_summary_name_token(db, task)
    return report_dir / f"{name_token}-{timestamp}-{task.task_id[:8]}.xlsx"


def _build_summary_name_token(db: Session, task: TestTask) -> str:
    """Build a human-readable summary filename token for one task."""
    if task.test_type == TestType.EZDFS.value:
        module_name = _extract_ezdfs_module_name(task) or task.target_name
        return sanitize_path_token(module_name)

    if task.test_type == TestType.RTD.value:
        line_name = normalize_target_line_name(task.target_name)
        config = db.query(RtdConfig).filter(RtdConfig.line_name == line_name).first()
        return sanitize_path_token(config.business_unit if config and config.business_unit else line_name)

    return sanitize_path_token(task.target_name or task.test_type)


def _write_rtd_rule_raw_files(
    raw_root_dir: Path,
    task: TestTask,
    line_token: str,
    raw_outputs_by_rule: dict[str, str],
) -> Path:
    raw_task_dir = raw_root_dir / task.task_id
    raw_task_dir.mkdir(parents=True, exist_ok=True)

    used_file_names: set[str] = set()
    index_payload: dict[str, dict[str, str] | str] = {
        "task_id": task.task_id,
        "line_name": normalize_target_line_name(task.target_name),
        "rule_files": {},
    }

    for rule_name, output in raw_outputs_by_rule.items():
        normalized_rule_name = str(rule_name or "").strip()
        if not normalized_rule_name:
            continue
        file_name = _build_unique_rtd_rule_raw_file_name(line_token, normalized_rule_name, used_file_names)
        (raw_task_dir / file_name).write_text(str(output or ""), encoding="utf-8")
        index_payload["rule_files"][normalized_rule_name] = file_name

    meta_path = raw_task_dir / "_meta.txt"
    meta_content = "\n".join(
        [
            f"task_id={task.task_id}",
            f"test_type={task.test_type}",
            f"action_type={task.action_type}",
            f"target_name={task.target_name}",
            f"status={task.status}",
            f"requested_at={task.requested_at.isoformat()}",
            f"line={normalize_target_line_name(task.target_name)}",
        ]
    )
    meta_path.write_text(meta_content, encoding="utf-8")
    (raw_task_dir / "index.json").write_text(
        json.dumps(index_payload, ensure_ascii=True, indent=2),
        encoding="utf-8",
    )
    return meta_path


def _write_ezdfs_raw_files(
    raw_root_dir: Path,
    task: TestTask,
    raw_output: str,
) -> Path:
    raw_task_dir = raw_root_dir / task.task_id
    raw_task_dir.mkdir(parents=True, exist_ok=True)
    command_text, detail_text = _split_ezdfs_raw_output(raw_output)

    meta_path = raw_task_dir / "_meta.txt"
    meta_lines = [
        f"task_id={task.task_id}",
        f"test_type={task.test_type}",
        f"action_type={task.action_type}",
        f"target_name={task.target_name}",
        f"status={task.status}",
        f"requested_at={task.requested_at.isoformat()}",
    ]
    if command_text:
        meta_lines.append(f"command={command_text}")
    meta_content = "\n".join(meta_lines)
    meta_path.write_text(meta_content, encoding="utf-8")
    raw_file_name = _build_ezdfs_raw_file_name(task)
    (raw_task_dir / raw_file_name).write_text(detail_text, encoding="utf-8")
    return meta_path


def _build_unique_rtd_rule_raw_file_name(
    line_token: str,
    rule_name: str,
    used_file_names: set[str],
) -> str:
    base_name = f"{line_token}-{sanitize_path_token(rule_name)}"
    file_name = f"{base_name}.txt"
    sequence = 2
    while file_name in used_file_names:
        file_name = f"{base_name}-{sequence}.txt"
        sequence += 1
    used_file_names.add(file_name)
    return file_name


def _split_ezdfs_raw_output(raw_output: str) -> tuple[str, str]:
    """Split ezDFS aggregate raw text into command metadata and plain detail body."""
    command_text = ""
    detail_lines: list[str] = []
    for line in str(raw_output or "").splitlines():
        if not command_text and line.startswith("command="):
            command_text = line.split("=", 1)[1].strip()
            continue
        detail_lines.append(line)
    return command_text, "\n".join(detail_lines).strip()


def _build_ezdfs_raw_file_name(task: TestTask) -> str:
    """Build a stable ezDFS raw txt filename from the selected rule name."""
    rule_name = _extract_ezdfs_rule_name(task)
    rule_token = sanitize_path_token(rule_name) if rule_name else "raw"
    return f"{rule_token}.txt"


def _extract_rtd_rule_name(task: TestTask) -> str:
    try:
        requested_payload = json.loads(task.requested_payload_json or "{}")
    except (json.JSONDecodeError, ValueError):
        return ""

    nested_payload = (
        requested_payload.get("payload")
        if isinstance(requested_payload.get("payload"), dict)
        else requested_payload
    )
    selected_rule = str(
        nested_payload.get("selected_rule")
        or requested_payload.get("rule_name")
        or ""
    ).strip()
    if selected_rule:
        return selected_rule

    selected_rule_targets = nested_payload.get("selected_rule_targets", [])
    if isinstance(selected_rule_targets, list):
        for item in selected_rule_targets:
            rule_name = str(item.get("rule_name", "")).strip()
            if rule_name:
                return rule_name
    return ""


def _extract_ezdfs_rule_name(task: TestTask) -> str:
    """Extract the selected ezDFS rule name from one stored task payload."""
    try:
        requested_payload = json.loads(task.requested_payload_json or "{}")
    except (json.JSONDecodeError, ValueError):
        return ""

    nested_payload = (
        requested_payload.get("payload")
        if isinstance(requested_payload.get("payload"), dict)
        else requested_payload
    )
    return str(
        requested_payload.get("rule_name")
        or nested_payload.get("selected_rule")
        or ""
    ).strip()


def _extract_ezdfs_module_name(task: TestTask) -> str:
    """Extract the selected ezDFS module name from one stored task payload."""
    try:
        requested_payload = json.loads(task.requested_payload_json or "{}")
    except (json.JSONDecodeError, ValueError):
        return ""

    nested_payload = (
        requested_payload.get("payload")
        if isinstance(requested_payload.get("payload"), dict)
        else requested_payload
    )
    return str(
        requested_payload.get("module_name")
        or nested_payload.get("selected_module")
        or ""
    ).strip()
