from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
import re

from fastapi import HTTPException
from openpyxl import Workbook
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.models.entities import RtdConfig, TestTask
from app.services.ezdfs_report_custom import build_ezdfs_test_report_file
from app.services.rtd_report_custom import build_rtd_test_report_file
from app.services.session_service import get_runtime_session_payload
from app.utils.enums import TaskStatus, TestType

settings = get_settings()


def _task_dir(task: TestTask) -> Path:
    base = Path(settings.result_base_path)
    return base / task.test_type.lower() / task.task_id


def _ensure_task_dir(task: TestTask) -> Path:
    path = _task_dir(task)
    path.mkdir(parents=True, exist_ok=True)
    return path


def generate_raw_file(
    db: Session,
    task: TestTask,
    raw_output: str | None = None,
    raw_outputs_by_rule: dict[str, str] | None = None,
) -> Path:
    if task.status != TaskStatus.DONE.value:
        raise HTTPException(status_code=409, detail="Task is not completed yet")

    line_token = _sanitize_path_token(_normalize_target_line_name(task.target_name))
    rule_token = _sanitize_path_token(_extract_rtd_rule_name(task)) if task.test_type == "RTD" else ""
    timestamp = (task.ended_at or task.started_at or task.requested_at or datetime.now()).strftime("%Y%m%d_%H%M%S")
    task_dir = Path(settings.result_base_path) / task.test_type.lower() / "raw" / _sanitize_path_token(task.user_id)
    task_dir.mkdir(parents=True, exist_ok=True)

    if (
        task.test_type == TestType.RTD.value
        and task.action_type in {"TEST", "RETEST"}
        and isinstance(raw_outputs_by_rule, dict)
        and raw_outputs_by_rule
    ):
        meta_path = _write_rtd_rule_raw_files(task_dir, task, line_token, raw_outputs_by_rule)
        task.raw_result_path = str(meta_path)
        db.add(task)
        db.commit()
        db.refresh(task)
        return meta_path

    if task.test_type == TestType.EZDFS.value and task.action_type in {"TEST", "RETEST"}:
        meta_path = _write_ezdfs_raw_files(task_dir, task, raw_output or "")
        task.raw_result_path = str(meta_path)
        db.add(task)
        db.commit()
        db.refresh(task)
        return meta_path

    file_stem = (
        f"{line_token}-{rule_token}-{timestamp}-{task.task_id[:8]}"
        if rule_token
        else f"{line_token}-{timestamp}-{task.task_id[:8]}"
    )
    file_path = task_dir / f"{file_stem}.txt"
    default_logs = [
        "log=Execution completed successfully.",
        "log=This raw data file was generated by backend execution flow.",
    ]
    content = "\n".join(
        [
            f"task_id={task.task_id}",
            f"test_type={task.test_type}",
            f"action_type={task.action_type}",
            f"target_name={task.target_name}",
            f"status={task.status}",
            f"requested_at={task.requested_at.isoformat()}",
            *([raw_output] if raw_output else default_logs),
        ]
    )
    file_path.write_text(content, encoding="utf-8")
    task.raw_result_path = str(file_path)
    db.add(task)
    db.commit()
    db.refresh(task)
    return file_path


def generate_summary_file(db: Session, task: TestTask) -> Path:
    if task.status != TaskStatus.DONE.value:
        raise HTTPException(status_code=409, detail="Task is not completed yet")

    file_path = _build_summary_output_path(db, task)

    if task.test_type == TestType.EZDFS.value:
        runtime_payload = get_runtime_session_payload(db, task.user_id, TestType.EZDFS)
        fallback_major_change_items = (
            runtime_payload.get("major_change_items")
            if isinstance(runtime_payload.get("major_change_items"), dict)
            else {}
        )
        build_ezdfs_test_report_file(task, file_path, None, fallback_major_change_items)
        task.summary_result_path = str(file_path)
        db.add(task)
        db.commit()
        db.refresh(task)
        return file_path

    if task.test_type == TestType.RTD.value:
        runtime_payload = get_runtime_session_payload(db, task.user_id, TestType.RTD)
        fallback_major_change_items = (
            runtime_payload.get("major_change_items")
            if isinstance(runtime_payload.get("major_change_items"), dict)
            else {}
        )
        build_rtd_test_report_file([task], file_path, fallback_major_change_items)
        task.summary_result_path = str(file_path)
        db.add(task)
        db.commit()
        db.refresh(task)
        return file_path

    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "summary"
    rows = [
        ("task_id", task.task_id),
        ("test_type", task.test_type),
        ("action_type", task.action_type),
        ("target_name", task.target_name),
        ("status", task.status),
        ("requested_at", task.requested_at.isoformat()),
        ("started_at", task.started_at.isoformat() if task.started_at else ""),
        ("ended_at", task.ended_at.isoformat() if task.ended_at else ""),
        ("message", task.message),
    ]
    for key, value in rows:
        sheet.append([key, value])

    workbook.save(file_path)
    task.summary_result_path = str(file_path)
    db.add(task)
    db.commit()
    db.refresh(task)
    return file_path


def get_existing_download_path(task: TestTask, kind: str) -> Path:
    if kind == "raw":
        if not task.raw_result_path:
            raise HTTPException(status_code=404, detail="Raw result file not found")
        path = Path(task.raw_result_path)
    else:
        if not task.summary_result_path:
            raise HTTPException(status_code=404, detail="Summary result file not found")
        path = Path(task.summary_result_path)

    if not path.exists():
        raise HTTPException(status_code=404, detail="Result file does not exist")

    return path


def get_rtd_raw_rule_file_map(task: TestTask) -> dict[str, Path]:
    """
    Return saved per-rule raw txt files for one RTD test task.

    RTD raw data is stored as:
    - `<raw_root>/<task_id>/_meta.txt`
    - `<raw_root>/<task_id>/index.json`
    - `<raw_root>/<task_id>/<line>-<rule>.txt`

    If `index.json` is missing, the task is treated as not having valid RTD
    rule raw files.
    """
    if not task.raw_result_path:
        return {}

    meta_path = Path(task.raw_result_path)
    raw_task_dir = meta_path.parent
    index_path = raw_task_dir / "index.json"
    if not index_path.exists():
        return {}

    try:
        index_payload = json.loads(index_path.read_text(encoding="utf-8"))
    except Exception:  # noqa: BLE001
        return {}

    rule_files = index_payload.get("rule_files", {})
    result: dict[str, Path] = {}
    for rule_name, file_name in rule_files.items():
        normalized_rule_name = str(rule_name or "").strip()
        normalized_file_name = str(file_name or "").strip()
        if not normalized_rule_name or not normalized_file_name:
            continue
        file_path = raw_task_dir / normalized_file_name
        if file_path.exists():
            result[normalized_rule_name] = file_path
    return result


def get_ezdfs_raw_content_path(task: TestTask) -> Path | None:
    """Return the saved ezDFS rule-named raw content txt path for one ezDFS test task."""
    if not task.raw_result_path:
        return None

    meta_path = Path(task.raw_result_path)
    raw_task_dir = meta_path.parent
    raw_path = raw_task_dir / _build_ezdfs_raw_file_name(task)
    if raw_path.exists():
        return raw_path
    return None


def generate_aggregate_rtd_summary_file(
    db: Session,
    user_id: str,
    target_lines: list[str],
) -> Path:
    if not target_lines:
        raise HTTPException(status_code=422, detail="target_lines is required")

    target_set = list(dict.fromkeys(target_lines))
    tasks = (
        db.query(TestTask)
        .filter(
            TestTask.user_id == user_id,
            TestTask.test_type == "RTD",
            TestTask.target_name.in_(target_set),
            TestTask.action_type.in_(["TEST", "RETEST"]),
            TestTask.status == TaskStatus.DONE.value,
        )
        .order_by(TestTask.requested_at.desc(), TestTask.id.desc())
        .all()
    )

    if not tasks:
        raise HTTPException(status_code=404, detail="No RTD test results found for selected target lines")

    runtime_payload = get_runtime_session_payload(db, user_id, TestType.RTD)
    fallback_major_change_items = (
        runtime_payload.get("major_change_items")
        if isinstance(runtime_payload.get("major_change_items"), dict)
        else {}
    )
    selected_rule_targets = (
        runtime_payload.get("selected_rule_targets")
        if isinstance(runtime_payload.get("selected_rule_targets"), list)
        else []
    )
    selected_rule_names = list(
        dict.fromkeys(
            str(item.get("rule_name") or "").strip()
            for item in selected_rule_targets
            if str(item.get("rule_name") or "").strip()
        )
    )

    report_dir = Path(settings.result_base_path) / "rtd" / "reports" / _sanitize_path_token(user_id)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    business_unit_token = _build_business_unit_token(db, target_set)
    output_path = report_dir / f"{business_unit_token}-{timestamp}.xlsx"
    return build_rtd_test_report_file(
        tasks,
        output_path,
        fallback_major_change_items,
        selected_rule_names,
    )


def generate_aggregate_ezdfs_summary_file(
    db: Session,
    user_id: str,
    module_name: str,
    task_ids: list[str],
) -> Path:
    if not module_name:
        raise HTTPException(status_code=422, detail="module_name is required")
    if not task_ids:
        raise HTTPException(status_code=422, detail="task_ids is required")

    ordered_task_ids = list(dict.fromkeys(task_ids))
    tasks = (
        db.query(TestTask)
        .filter(
            TestTask.user_id == user_id,
            TestTask.test_type == "EZDFS",
            TestTask.task_id.in_(ordered_task_ids),
            TestTask.action_type.in_(["TEST", "RETEST"]),
        )
        .all()
    )
    done_tasks = [task for task in tasks if task.status == TaskStatus.DONE.value]
    done_tasks.sort(key=lambda task: (task.requested_at, task.id), reverse=True)
    if not done_tasks:
        raise HTTPException(status_code=404, detail="No completed ezDFS test results found for selected rules")

    runtime_payload = get_runtime_session_payload(db, user_id, TestType.EZDFS)
    selected_rules = (
        runtime_payload.get("selected_rules")
        if isinstance(runtime_payload.get("selected_rules"), list)
        else []
    )
    selected_rule_names = list(
        dict.fromkeys(
            str(item.get("rule_name") or "").strip()
            for item in selected_rules
            if isinstance(item, dict) and str(item.get("rule_name") or "").strip()
        )
    )
    if not selected_rule_names:
        selected_rule = str(runtime_payload.get("selected_rule") or "").strip()
        if selected_rule:
            selected_rule_names = [selected_rule]

    report_dir = Path(settings.result_base_path) / "ezdfs" / "reports" / _sanitize_path_token(user_id)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_path = report_dir / f"{_sanitize_path_token(module_name)}-{timestamp}.xlsx"
    fallback_major_change_items = (
        runtime_payload.get("major_change_items")
        if isinstance(runtime_payload.get("major_change_items"), dict)
        else {}
    )
    return build_ezdfs_test_report_file(
        done_tasks,
        output_path,
        selected_rule_names,
        fallback_major_change_items,
    )


def _build_target_line_token(target_lines: list[str]) -> str:
    normalized = [_sanitize_path_token(_normalize_target_line_name(line)) for line in target_lines if line]
    if not normalized:
        return "rtd_test_report"

    token = "__".join(normalized)
    if len(token) > 100:
        token = f"{normalized[0]}__and_{len(normalized) - 1}_more"
    return token


def _build_business_unit_token(db: Session, target_lines: list[str]) -> str:
    business_units: list[str] = []
    for line in target_lines:
        normalized_line = _normalize_target_line_name(line)
        config = db.query(RtdConfig).filter(RtdConfig.line_name == normalized_line).first()
        if config and config.business_unit:
            business_units.append(config.business_unit)

    normalized_units = list(dict.fromkeys(_sanitize_path_token(unit) for unit in business_units if unit))
    if not normalized_units:
        return "business_unit"
    if len(normalized_units) == 1:
        return normalized_units[0]
    return f"{normalized_units[0]}__and_{len(normalized_units) - 1}_more"


def _normalize_target_line_name(line_name: str) -> str:
    if line_name.endswith("_TARGET"):
        return line_name[: -len("_TARGET")]
    return line_name


def _build_summary_output_path(db: Session, task: TestTask) -> Path:
    """Build the per-task summary xlsx path under `results/<type>/reports/<user>/`."""
    report_dir = Path(settings.result_base_path) / task.test_type.lower() / "reports" / _sanitize_path_token(task.user_id)
    report_dir.mkdir(parents=True, exist_ok=True)

    timestamp = (task.ended_at or task.started_at or task.requested_at or datetime.now()).strftime("%Y%m%d_%H%M%S")
    name_token = _build_summary_name_token(db, task)
    return report_dir / f"{name_token}-{timestamp}-{task.task_id[:8]}.xlsx"


def _build_summary_name_token(db: Session, task: TestTask) -> str:
    """Build a human-readable summary filename token for one task."""
    if task.test_type == TestType.EZDFS.value:
        module_name = _extract_ezdfs_module_name(task) or task.target_name
        return _sanitize_path_token(module_name)

    if task.test_type == TestType.RTD.value:
        line_name = _normalize_target_line_name(task.target_name)
        config = db.query(RtdConfig).filter(RtdConfig.line_name == line_name).first()
        return _sanitize_path_token(config.business_unit if config and config.business_unit else line_name)

    return _sanitize_path_token(task.target_name or task.test_type)


def _sanitize_path_token(value: str) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9._-]+", "_", str(value or "").strip())
    return sanitized.strip("._-") or "report"


def _write_rtd_rule_raw_files(
    raw_root_dir: Path,
    task: TestTask,
    line_token: str,
    raw_outputs_by_rule: dict[str, str],
) -> Path:
    raw_task_dir = raw_root_dir / task.task_id
    raw_task_dir.mkdir(parents=True, exist_ok=True)

    used_file_names: set[str] = set()
    index_payload: dict[str, dict[str, str] | str] = {
        "task_id": task.task_id,
        "line_name": _normalize_target_line_name(task.target_name),
        "rule_files": {},
    }

    for rule_name, output in raw_outputs_by_rule.items():
        normalized_rule_name = str(rule_name or "").strip()
        if not normalized_rule_name:
            continue
        file_name = _build_unique_rtd_rule_raw_file_name(line_token, normalized_rule_name, used_file_names)
        (raw_task_dir / file_name).write_text(str(output or ""), encoding="utf-8")
        index_payload["rule_files"][normalized_rule_name] = file_name

    meta_path = raw_task_dir / "_meta.txt"
    meta_content = "\n".join(
        [
            f"task_id={task.task_id}",
            f"test_type={task.test_type}",
            f"action_type={task.action_type}",
            f"target_name={task.target_name}",
            f"status={task.status}",
            f"requested_at={task.requested_at.isoformat()}",
            f"line={_normalize_target_line_name(task.target_name)}",
        ]
    )
    meta_path.write_text(meta_content, encoding="utf-8")
    (raw_task_dir / "index.json").write_text(
        json.dumps(index_payload, ensure_ascii=True, indent=2),
        encoding="utf-8",
    )
    return meta_path


def _write_ezdfs_raw_files(
    raw_root_dir: Path,
    task: TestTask,
    raw_output: str,
) -> Path:
    raw_task_dir = raw_root_dir / task.task_id
    raw_task_dir.mkdir(parents=True, exist_ok=True)
    command_text, detail_text = _split_ezdfs_raw_output(raw_output)

    meta_path = raw_task_dir / "_meta.txt"
    meta_lines = [
        f"task_id={task.task_id}",
        f"test_type={task.test_type}",
        f"action_type={task.action_type}",
        f"target_name={task.target_name}",
        f"status={task.status}",
        f"requested_at={task.requested_at.isoformat()}",
    ]
    if command_text:
        meta_lines.append(f"command={command_text}")
    meta_content = "\n".join(meta_lines)
    meta_path.write_text(meta_content, encoding="utf-8")
    raw_file_name = _build_ezdfs_raw_file_name(task)
    (raw_task_dir / raw_file_name).write_text(detail_text, encoding="utf-8")
    return meta_path


def _build_unique_rtd_rule_raw_file_name(
    line_token: str,
    rule_name: str,
    used_file_names: set[str],
) -> str:
    base_name = f"{line_token}-{_sanitize_path_token(rule_name)}"
    file_name = f"{base_name}.txt"
    sequence = 2
    while file_name in used_file_names:
        file_name = f"{base_name}-{sequence}.txt"
        sequence += 1
    used_file_names.add(file_name)
    return file_name


def _split_ezdfs_raw_output(raw_output: str) -> tuple[str, str]:
    """Split ezDFS aggregate raw text into command metadata and plain detail body."""
    command_text = ""
    detail_lines: list[str] = []
    for line in str(raw_output or "").splitlines():
        if not command_text and line.startswith("command="):
            command_text = line.split("=", 1)[1].strip()
            continue
        detail_lines.append(line)
    return command_text, "\n".join(detail_lines).strip()


def _build_ezdfs_raw_file_name(task: TestTask) -> str:
    """Build a stable ezDFS raw txt filename from the selected rule name."""
    rule_name = _extract_ezdfs_rule_name(task)
    rule_token = _sanitize_path_token(rule_name) if rule_name else "raw"
    return f"{rule_token}.txt"


def _extract_rtd_rule_name(task: TestTask) -> str:
    try:
        requested_payload = json.loads(task.requested_payload_json or "{}")
    except Exception:  # noqa: BLE001
        return ""

    nested_payload = (
        requested_payload.get("payload")
        if isinstance(requested_payload.get("payload"), dict)
        else requested_payload
    )
    selected_rule = str(
        nested_payload.get("selected_rule")
        or requested_payload.get("rule_name")
        or ""
    ).strip()
    if selected_rule:
        return selected_rule

    selected_rule_targets = nested_payload.get("selected_rule_targets", [])
    if isinstance(selected_rule_targets, list):
        for item in selected_rule_targets:
            rule_name = str(item.get("rule_name", "")).strip()
            if rule_name:
                return rule_name
    return ""


def _extract_ezdfs_rule_name(task: TestTask) -> str:
    """Extract the selected ezDFS rule name from one stored task payload."""
    try:
        requested_payload = json.loads(task.requested_payload_json or "{}")
    except Exception:  # noqa: BLE001
        return ""

    nested_payload = (
        requested_payload.get("payload")
        if isinstance(requested_payload.get("payload"), dict)
        else requested_payload
    )
    return str(
        requested_payload.get("rule_name")
        or nested_payload.get("selected_rule")
        or ""
    ).strip()


def _extract_ezdfs_module_name(task: TestTask) -> str:
    """Extract the selected ezDFS module name from one stored task payload."""
    try:
        requested_payload = json.loads(task.requested_payload_json or "{}")
    except Exception:  # noqa: BLE001
        return ""

    nested_payload = (
        requested_payload.get("payload")
        if isinstance(requested_payload.get("payload"), dict)
        else requested_payload
    )
    return str(
        requested_payload.get("module_name")
        or nested_payload.get("selected_module")
        or ""
    ).strip()
